# Generated by Django 4.0.4 on 2022-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
