# Generated by Django 4.0.4 on 2022-05-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, default="''", max_length=500, null=True),
        ),
    ]
