# Generated by Django 4.0.4 on 2022-05-30 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0003_list_x_coordinate_list_y_coordinate'),
        ('space', '0002_space_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(blank=True, max_length=75, null=True)),
                ('text', models.CharField(blank=True, max_length=75, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_cards', to='list.list')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_cards', to='space.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
