# Generated by Django 4.0.4 on 2022-06-01 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0001_initial'),
        ('space', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(blank=True, max_length=75, null=True)),
                ('text', models.CharField(blank=True, max_length=75, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_cards', to='list.list')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_cards', to='space.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
