# Generated by Django 4.0.4 on 2022-06-01 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_card_end_date_remove_card_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
