# Generated by Django 4.0.4 on 2022-06-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
