# Generated by Django 4.0.4 on 2022-05-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
