# Generated by Django 4.0.4 on 2022-05-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='x_coordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='y_coordinate',
            field=models.IntegerField(default=0),
        ),
    ]
