# Generated by Django 4.0.4 on 2022-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
