# Generated by Django 4.0.4 on 2022-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
